Added exception
hovel/django-oauth-client pull request #1
Opened 2021-09-12 18:13 UTC by aryadovoy

2021-09-12 20:39 UTC, lampslave commented on oauth_client/exceptions.py
> +from rest_framework.exceptions import APIException
rest_framework тут вообще никаким боком не участвует, наследуйся от обычного Exception

2021-09-12 20:42 UTC, lampslave commented on oauth_client/utils.py
> +    if not bool(locked):
Выброс исключения должен быть настраиваемым и по дефолту исключение выбрасываться не должно

2021-09-12 20:42 UTC, lampslave requested changes
См. комментарии

2021-09-12 20:51 UTC, lampslave commented
Вообще суть этого всего в том, чтобы при невозможности залочить интеграцию была сделана вторая попытка через некоторое (желательно настраиваемое) время. Чтоб параллельные задачки друг за другом выполнялись таким образом.

2021-09-14 09:31 UTC, aryadovoy commented
Добавлены настройки в settings.py проектов

2024-03-08 05:50 UTC, closed without merging